### PR TITLE
First release of competition code

### PR DESCRIPTION
**Pull request by mwoden**

### CODE REVIEW

**Comment by msoucy** [comment]
Yeah I'm not reading all this. Seems to be building etc...

**Comment by mwoden** [comment]
I wasn't sure if Travis did anything on this branch. I've been swamped with other stuff, so I just want to get this ready for loading on to the pit laptop tomorrow. Thank you for handling it. Promise I wasn't throwing it over the wall to you!

**Comment by msoucy** [comment]
Nah, it's all good. You know I don't have a robot to test with anyways. I've watched the code develop, so I'm confident that you only made the request because it's semistable right now.

**Comment by mwoden** [comment]
More than semi-stable. Except for the wings, all stuff is tested, and the autonomous code works beautifully.

**Pull request merged**
